<?php

namespace App\Livewire\Search;

use Livewire\Component;

class CalculatorSearch extends Component
{
    public $search = '';
    public $suggestions = [];
    public $showSuggestions = false;
    public $highlightIndex = -1;

    protected $searchCalculators = [
        // Pets Calculator
        ["Puppy Weight Calculator", "puppy-weight-calculator", "Pets"],
        ["Pearson Age Calculator", "pearson-age-calculator", "Pets"],
        ["Cat Age Calculator", "cat-age-calculator", "Pets"],
        ["Dog Pregnancy Calculator", "dog-pregnancy-calculator", "Pets"],
        ["Benadryl for Dogs Calculator", "benadryl-for-dogs-calculator", "Pets"],
        ["Dog Crate Size Calculator", "dog-crate-size-calculator", "Pets"],
        ["Cat Calorie Calculator", "cat-calorie-calculator", "Pets"],
        ["Dog Food Calculator", "dog-food-calculator", "Pet"],
        // Time Calculators
        ["Time Calculator", "time-calculator", "Date & Time"],
        ["Time Card Calculator", "time-card-calculator", "Date & Time"],
        ["Time Span Calculator", "time-span-calculator", "Date & Time"],
        ["Time Duration Calculator", "time-duration-calculator", "Date & Time"],
        ["Add Time Calculator", "add-time-calculator", "Date & Time"],
        ["Military Time Converter", "military-time-converter", "Date & Time"],
        ["Reading Time Calculator", "reading-time-calculator", "Date & Time"],
        ["Elapsed Time Calculator", "elapsed-time-calculator", "Date & Time"],
        ["Time Until Calculator", "time-until-calculator", "Date & Time"],
        ["Time Ago Calculator", "hours-ago-calculator", "Date & Time"],
        ["Date Calculator", "date-calculator", "Date & Time"],
        ["Business Days Calculator", "business-days-calculator", "Date & Time"],
        ["Lead Time Calculator", "lead-time-calculator", "Date & Time"],
        ["Date Duration Calculator", "date-duration-calculator", "Date & Time"],
        ["Month Calculator", "month-calculator", "Date & Time"],
        ["Deadline Calculator", "deadline-calculator", "Date & Time"],
        ["Working Days Calculator", "working-days-calculator", "Date & Time"],
        ["Today's Date", "todays-date", "Date & Time"],
        ["Birth Year Calculator", "birth-year-calculator", "Date & Time"],
        ["Days Until Calculator", "days-until-calculator", "Date & Time"],
        ["Week Calculator", "week-calculator", "Date & Time"],
        ["Days From Today Calculator", "days-from-today", "Date & Time"],
        ["Weeks From Today Calculator", "weeks-from-today", "Date & Time"],
        ["Years From Today Calculator", "years-from-today", "Date & Time"],
        ["Hours From Now Calculator", "hours-from-now", "Date & Time"],
        ["Years Ago Calculator", "years-ago-calculator", "Date & Time"],
        ["Weeks Ago Calculator", "weeks-ago-calculator", "Date & Time"],
        ["Julian Date Calendar", "julians-date-calculator", "Date & Time"],
        ["Months From Now Calculator", "months-from-now", "Date & Time"],
        ["Days Since Date Calculator", "days-since-date-calculator", "Date & Time"],
        ["Days Ago Calculator", "days-ago-calculator", "Date & Time"],
        ["Days Left in 2025", "days-left-in-the-year", "Date & Time"],
        ["Weeks Left in 2025", "weeks-left-in-the-year", "Date & Time"],
        ["Months Left in 2025", "months-left-in-the-year", "Date & Time"],
        ["Days Until Birthday", "how-many-days-until-my-birthday", "Date & Time"],
        // Construction Calculators
        ["Square Footage Calculator", "square-footage-calculator", "Construction"],
        ["Cubic Feet Calculator", "cubic-feet-calculator", "Construction"],
        ["Feet and Inches Calculator", "feet-and-inches-calculator", "Construction"],
        ["Cubic Yard Calculator", "cubic-yard-calculator", "Construction"],
        ["Wallpaper Calculator", "wallpaper-calculator", "Construction"],
        ["Square Yards Calculator", "square-yards-calculator", "Construction"],
        ["Square Meter Calculator", "square-meter-calculator", "Construction"],
        ["Room Size Calculator", "room-size-calculator", "Construction"],
        ["Square Inches Calculator", "square-inches-calculator", "Construction"],
        ["Carpet Calculator", "carpet-calculator", "Construction"],
        ["Tank Volume Calculator", "tank-volume-calculator", "Construction"],
        ["Pipe Volume Calculator", "pipe-volume-calculator", "Construction"],
        ["Cylinder Volume Calculator", "cylinder-volume-calculator", "Construction"],
        ["Gravel Calculator", "gravel-calculator", "Construction"],
        ["Mulch Calculator", "mulch-calculator", "Construction"],
        ["Sand Calculator", "sand-calculator", "Construction"],
        ["Asphalt Calculator", "asphalt-calculator", "Construction"],
        ["Concrete Calculator", "concrete-calculator", "Construction"],
        ["Top Soil Calculator", "topsoil-calculator", "Construction"],
        ["Rebar Calculator", "rebar-calculator", "Construction"],
        ["Sod Calculator", "sod-calculator", "Construction"],
        ["Roof Pitch Calculator", "roof-pitch-calculator", "Construction"],
        ["Paver Calculator", "paver-calculator", "Construction"],
        ["Fence Calculator", "fence-calculator", "Construction"],
        ["Acreage Calculator", "acreage-calculator", "Construction"],
        ["Tile Calculator", "tile-calculator", "Construction"],
        ["Flooring Calculator", "flooring-calculator", "Construction"],
        ["MS Plate Weight Calculator", "ms-plate-weight-calculator", "Construction"],
        ["Price Per Square Foot Calculator", "price-per-square-foot-calculator", "Construction"],
        ["Material Calculator", "material-calculator", "Construction"],
        ["Retaining Wall Calculator", "retaining-wall-calculator", "Construction"],
        ["Stud Calculator", "stud-calculator", "Construction"],
        ["Ramp Calculator", "ramp-calculator", "Construction"],
        ["Brick Calculator", "brick-calculator", "Construction"],
        ["Stone Calculator", "stone-calculator", "Construction"],
        ["Metal Roof Cost Calculator", "metal-roof-cost-calculator", "Construction"],
        ["Roof Replacement Cost Calculator", "roof-replacement-cost-calculator", "Construction"],
        ["Concrete Block Calculator", "concrete-block-calculator", "Construction"],
        ["Framing Calculator", "framing-calculator", "Construction"],
        ["Roofing Calculator", "roofing-calculator", "Construction"],
        ["Decking Calculator", "decking-calculator", "Construction"],
        ["Sonotube Calculator", "sonotube-calculator", "Construction"],
        // Statistics calculator
        ["Probability Calculator", "probability-calculator", "Statistics"],
        ["Hypergeometric Calculator", "hypergeometric-calculator", "Statistics"],
        ["Poisson Distribution Calculator", "poisson-distribution-calculator", "Statistics"],
        ["Binomial Distribution Calculator", "binomial-distribution-calculator", "Statistics"],
        ["Coin Flip Calculator", "coin-flip-calculator", "Statistics"],
        ["Empirical Probability Calculator", "empirical-probability-calculator", "Statistics"],
        ["P-Hat Calculator", "p-hat-calculator", "Statistics"],
        ["Empirical Rule Calculator", "empirical-rule-calculator", "Statistics"],
        ["Stem and Leaf Plot Calculator", "stem-leaf-plot-calculator", "Statistics"],
        ["Box Plot Calculator", "box-plot-calculator", "Statistics"],
        ["Scatter Plot Maker", "scatter-plot-maker", "Statistics"],
        ["Residual Plot Calculator", "residual-plot-calculator", "Statistics"],
        ["Pie Chart Calculator", "pie-chart-calculator", "Statistics"],
        ["Coefficient of Variation Calculator", "coefficient-of-variation-calculator", "Statistics"],
        ["Mean Median Mode Range Calculator", "mean-median-mode-range-calculator", "Statistics"],
        ["Quartile Calculator", "quartile-calculator", "Statistics"],
        ["Geometric Mean Calculator", "geometric-mean-calculator", "Statistics"],
        ["Harmonic Mean Calculator", "harmonic-mean-calculator", "Statistics"],
        ["IQR Calculator", "interquartile-range-calculator", "Statistics"],
        ["Mean Absolute Deviation Calculator", "mad-calculator", "Statistics"],
        ["Standard Deviation Calculator", "standard-deviation-calculator", "Statistics"],
        ["5 Number Summary Calculator", "5-five-number-summary-calculator", "Statistics"],
        ["Variance Calculator", "variance-calculator", "Statistics"],
        ["Midrange Calculator", "midrange-calculator", "Statistics"],
        ["Chebyshev's Theorem Calculator", "chebyshevs-theorem-calculator", "Statistics"],
        ["Coefficient of Determination Calculator (R-squared)", "coefficient-of-determination-calculator", "Statistics"],
        ["Correlation Coefficient Calculator", "correlation-coefficient-calculator", "Statistics"],
        ["Linear Regression Calculator", "linear-regression-calculator", "Statistics"],
        ["Outlier Calculator", "outlier-calculator", "Statistics"],
        ["Quadratic Regression Calculator", "quadratic-regression-calculator", "Statistics"],
        ["Combination Calculator", "combination-calculator", "Statistics"],
        ["Permutation Calculator", "permutation-calculator", "Statistics"],
        ["Binomial Coefficient Calculator", "binomial-coefficient-calculator", "Statistics"],
        ["Class Width Calculator", "class-width-calculator", "Statistics"],
        ["PERT Calculator", "pert-calculator", "Statistics"],
        ["Covariance Calculator", "covariance-calculator", "Statistics"],
        ["Sum of Squares Calculator", "sum-of-squares-calculator", "Statistics"],
        ["Point Estimate Calculator", "point-estimate-calculator", "Statistics"],
        ["Percentile Calculator", "percentile-calculator", "Statistics"],
        ["RSD Calculator", "rsd-calculator", "Statistics"],
        ["Percentile Rank Calculator", "percentile-rank-calculator", "Statistics"],
        ["Z Score to Percentile Calculator", "z-score-to-percentile", "Statistics"],
        ["Raw Score Calculator", "raw-score-calculator", "Statistics"],
        ["Pooled Variance Calculator", "pooled-variance-calculator", "Statistics"],
        ["SSE Calculator", "sse-calculator", "Statistics"],
        ["Residual Calculator", "residual-calculator", "Statistics"],
        ["Decile Calculator", "decile-calculator", "Statistics"],
        ["Sample Size Calculator", "sample-size-calculator", "Statistics"],
        ["Error Propagation Calculator", "error-propagation-calculator", "Statistics"],
        ["Z Score Calculator", "z-score-calculator", "Statistics"],
        ["Standard Error Calculator", "standard-error-calculator", "Statistics"],
        ["Confidence Interval Calculator", "confidence-interval-calculator", "Statistics"],
        ["Central Limit Theorem Calculator", "central-limit-theorem-calculator", "Statistics"],
        ["InvNorm Calculator", "invnorm-calculator", "Statistics"],
        ["Probability Density Function Calculator", "probability-density-function-calculator", "Statistics"],
        ["Normal Distribution Calculator", "normal-distribution-calculator", "Statistics"],
        ["Prediction Interval Calculator", "prediction-interval-calculator", "Statistics"],
        ["Sampling Distribution Calculator", "sample-distribution-calculator", "Statistics"],
        ["Chi-Square Calculator", "chi-square-calculator", "Statistics"],
        ["Critical Value Calculator", "critical-value-calculator", "Statistics"],
        ["Anova Calculator", "anova-calculator", "Statistics"],
        ["P Value Calculator", "p-value-calculator", "Statistics"],
        ["Degrees of Freedom Calculator", "degrees-of-freedom-calculator", "Statistics"],
        ["Test Statistic Calculator", "test-statistic-calculator", "Statistics"],
        ["Effect Size Calculator", "effect-size-calculator", "Statistics"],
        ["Expected Value Calculator", "expected-value-calculator", "Statistics"],
        ["Relative Frequency Calculator", "relative-frequency-calculator", "Statistics"],
        ["Shannon Diversity Index Calculator", "shannon-diversity-index-calculator", "Statistics"],
        ["Accuracy Calculator", "accuracy-calculator", "Statistics"],
        ["Relative Risk Calculator", "relative-risk-calculator", "Statistics"],
        // Chemistry calculator
        ["Ideal Gas Law Calculator", "ideal-gas-law-calculator", "Chemistry"],
        ["Charles Law Calculator", "charles-law-calculator", "Chemistry"],
        ["Partial Pressure Calculator", "partial-pressure-calculator", "Chemistry"],
        ["Boyle's Law Calculator", "boyles-law-calculator", "Chemistry"],
        ["Combined Gas Law Calculator", "combined-gas-law-calculator", "Chemistry"],
        ["STP Calculator", "stp-calculator", "Chemistry"],
        ["Vapor Pressure Calculator", "vapor-pressure-calculator", "Chemistry"],
        ["Molarity Calculator", "molarity-calculator", "Chemistry"],
        ["Dilution Calculator", "dilution-calculator", "Chemistry"],
        ["PPM Calculator", "ppm-calculator", "Chemistry"],
        ["Mass Percent Calculator", "mass-percent-calculator", "Chemistry"],
        ["ML to Moles Calculator", "ml-to-moles-calculator", "Chemistry"],
        ["Solution Dilution Calculator", "solution-dilution-calculator", "Chemistry"],
        ["Nernst Equation Calculator", "nernst-equation-calculator", "Chemistry"],
        ["pH Calculator", "ph-calculator", "Chemistry"],
        ["Equilibrium Constant Calculator", "equilibrium-constant-calculator", "Chemistry"],
        ["Redox Reaction Calculator", "redox-reaction-calculator", "Chemistry"],
        ["pKa to pH calculator", "pka-to-ph-calculator", "Chemistry"],
        ["Half Life Calculator", "half-life-calculator", "Chemistry"],
        ["CFU Calculator", "cfu-calculator", "Chemistry"],
        ["Rate Constant Calculator", "rate-constant-calculator", "Chemistry"],
        ["Mole Fraction Calculator", "mole-fraction-calculator", "Chemistry"],
        ["Electron Configuration Calculator", "electron-configuration-calculator", "Chemistry"],
        ["Titration Calculator", "titration-calculator", "Chemistry"],
        ["Atomic Mass Calculator", "atomic-mass-calculator", "Chemistry"],
        ["Molality Calculator", "molality-calculator", "Chemistry"],
        ["Average Atomic Mass Calculator", "average-atomic-mass-calculator", "Chemistry"],
        ["Bond Order Calculator", "bond-order-calculator", "Chemistry"],
        ["Percent Yield Calculator", "percent-yield-calculator", "Chemistry"],
        ["Theoretical Yield Calculator", "theoretical-yield-calculator", "Chemistry"],
        ["Empirical Formula Calculator", "empirical-formula-calculator", "Chemistry"],
        ["Molar Mass Calculator", "molar-mass-calculator", "Chemistry"],
        ["Limiting Reactant Calculator", "limiting-reactant-calculator", "Chemistry"],
        ["Stoichiometry Calculator", "stoichiometry-calculator", "Chemistry"],
        ["Mole Ratio Calculator", "mole-ratio-calculator", "Chemistry"],
        ["Calorimetry Calculator", "calorimetry-calculator", "Chemistry"],
        ["Activation Energy Calculator", "activation-energy-calculator", "Chemistry"],
        ["Gibbs Free Energy Calculator", "gibbs-free-energy-calculator", "Chemistry"],
        ["Entropy Calculator", "entropy-calculator", "Chemistry"],
        ["Mole Calculator", "mole-calculator", "Chemistry"],
        ["Molecular Formula Calculator", "molecular-formula-calculator", "Chemistry"],
        ["Formal Charge Calculator", "formal-charge-calculator", "Chemistry"],
        ["Grams to Moles Calculator", "grams-to-moles-calculator", "Chemistry"],
        ["Moles To Grams Calculator", "moles-to-grams-calculator", "Chemistry"],
        ["Atoms to Moles Calculator", "atoms-to-moles-calculator", "Chemistry"],
        ["Grams To Atoms Calculator", "grams-to-atoms-calculator", "Chemistry"],
        // Physics calculator
        ["Ohms Law Calculator", "ohms-law-calculator", "Physics"],
        ["Electric Field Calculator", "electric-field-calculator", "Physics"],
        ["Voltage Drop Calculator", "voltage-drop-calculator", "Physics"],
        ["Electricity Cost Calculator", "electricity-cost-calculator", "Physics"],
        ["Amp Hour Calculator", "amp-hour-calculator", "Physics"],
        ["Parallel Resistor Calculator", "parallel-resistor-calculator", "Physics"],
        ["Resistance Calculator", "resistance-calculator", "Physics"],
        ["Capacitance Calculator", "capacitance-calculator", "Physics"],
        ["Electric Flux calculator", "electric-flux-calculator", "Physics"],
        ["Electric Potential Calculator", "electric-potential-calculator", "Physics"],
        ["Amps to Watts Calculator", "amps-to-watts-calculator", "Physics"],
        ["Watts to Amps Calculator", "watts-to-amps-calculator", "Physics"],
        ["Acceleration Calculator", "acceleration-calculator", "Physics"],
        ["Average Velocity Calculator", "average-velocity-calculator", "Physics"],
        ["Instantaneous Velocity Calculator", "instantaneous-velocity-calculator", "Physics"],
        ["Angular Velocity Calculator", "angular-velocity-calculator", "Physics"],
        ["Displacement Calculator", "displacement-calculator", "Physics"],
        ["Instantaneous Rate of Change Calculator", "instantaneous-rate-of-change-calculator", "Physics"],
        ["Projectile Motion Calculator", "projectile-motion-calculator", "Physics"],
        ["Free Fall Calculator", "free-fall-calculator", "Physics"],
        ["Speed Distance Time Calculator", "speed-distance-time-calculator", "Physics"],
        ["Terminal Velocity Calculator", "terminal-velocity-calculator", "Physics"],
        ["Angular Acceleration Calculator", "angular-acceleration-calculator", "Physics"],
        ["Time of Flight Calculator", "time-of-flight-calculator", "Physics"],
        ["Average Speed Calculator", "average-speed-calculator", "Physics"],
        ["Wave Speed Calculator", "wave-speed-calculator", "Physics"],
        ["Time Dilation Calculator", "time-dilation-calculator", "Physics"],
        ["Speed of Sound Calculator", "speed-of-sound-calculator", "Physics"],
        ["Photon Energy Calculator", "photon-energy-calculator", "Physics"],
        ["Wavelength Calculator", "wavelength-calculator", "Physics"],
        ["Index of Refraction Calculator", "index-of-refraction-calculator", "Physics"],
        ["Snell's Law Calculator", "snells-law-calculator", "Physics"],
        ["Wave Period Calculator", "wave-period-calculator", "Physics"],
        ["Angle of Refraction Calculator", "angle-of-refraction-calculator", "Physics"],
        ["Quantum Number Calculator", "quantum-number-calculator", "Physics"],
        ["Velocity Calculator", "velocity-calculator", "Physics"],
        ["Kinematics Calculator", "kinematics-calculator", "Physics"],
        ["Enthalpy Calculator", "enthalpy-calculator", "Physics"],
        ["Spring Constant Calculator", "spring-constant-calculator", "Physics"],
        ["Transformer Calculator", "transformer-calculator", "Physics"],
        ["Constant of Proportionality Calculator", "constant-of-proportionality-calculator", "Physics"],
        ["Quarter Mile Calculator", "quarter-mile-calculator", "Physics"],
        ["Escape Velocity Calculator", "escape-velocity-calculator", "Physics"],
        ["Coulomb's Law Calculator", "coulombs-law-calculator", "Physics"],
        ["Solar Panel Calculator", "solar-panel-calculator", "Physics"],
        ["Arrow Speed Calculator", "arrow-speed-calculator", "Physics"],
        ["Tension Calculator", "tension-calculator", "Physics"],
        ["Air Density Calculator", "air-density-calculator", "Physics"],
        ["Beam Deflection Calculator", "beam-deflection-calculator", "Physics"],
        ["Wire Size Calculator", "wire-size-calculator", "Physics"],
        ["Efficiency Calculator", "efficiency-calculator", "Physics"],
        ["Volts To Joules Calculator", "volts-to-joules-calculator", "Physics"],
        ["FPE Calculator", "fpe-calculator", "Physics"],
        ["Relative Humidity Calculator", "relative-humidity-calculator", "Physics"],
        ["Friction Loss Calculator", "friction-loss-calculator", "Physics"],
        ["Orbital Period Calculator", "orbital-period-calculator", "Physics"],
        ["Newton's Law of Cooling Calculator", "newtons-law-of-cooling-calculator", "Physics"],
        ["DC Wire Size Calculator", "dc-wire-size-calculator", "Physics"],
        ["Density Altitude Calculator", "density-altitude-calculator", "Physics"],
        ["Kinetic Energy Calculator", "kinetic-energy-calculator", "Physics"],
        ["Torque Calculator", "torque-calculator", "Physics"],
        ["Horsepower Calculator", "horsepower-calculator", "Physics"],
        ["Momentum Calculator", "momentum-calculator", "Physics"],
        ["Work Calculator", "work-calculator", "Physics"],
        ["Force Calculator", "force-calculator", "Physics"],
        ["Potential Energy Calculator", "potential-energy-calculator", "Physics"],
        ["Power To Weight Ratio Calculator", "power-to-weight-ratio-calculator", "Physics"],
        ["Friction Calculator", "friction-calculator", "Physics"],
        ["Centripetal Force Calculator", "centripetal-force-calculator", "Physics"],
        ["Frictional Force Calculator", "frictional-force-calculator", "Physics"],
        ["Mechanical Energy Calculator", "mechanical-energy-calculator", "Physics"],
        ["Change in Momentum Calculator", "change-in-momentum-calculator", "Physics"],
        ["CC to HP Calculator", "cc-to-hp-calculator", "Physics"],
        ["Impulse Calculator", "impulse-calculator", "Physics"],
        ["WHP to HP Calculator", "whp-to-hp-calculator", "Physics"],
        ["Resultant Force Calculator", "resultant-force-calculator", "Physics"],
        ["Energy Cost Calculator", "energy-cost-calculator", "Physics"],
        ["Normal Force Calculator", "normal-force-calculator", "Physics"],
        ["Density Calculator", "density-calculator", "Physics"],
        ["Specific Heat Calculator", "specific-heat-calculator", "Physics"],
        ["Water Viscosity Calculator", "water-viscosity-calculator", "Physics"],
        ["Dew Point Calculator", "dew-point-calculator", "Physics"],
        ["Wet Bulb Calculator", "wet-bulb-calculator", "Physics"],
        ["Flow Rate Calculator", "flow-rate-calculator", "Physics"],
        ["Heat Index Calculator", "heat-index-calculator", "Physics"],
        ["Reynolds Number Calculator", "reynolds-number-calculator", "Physics"],
        ["Buoyancy Calculator", "buoyancy-calculator", "Physics"],
        ["Specific Gravity Calculator", "specific-gravity-calculator", "Physics"],
        ["Watt Calculator", "watt-calculator", "Physics"],
        ["Watt Hour Calculator", "watt-hour-calculator", "Physics"],
        ["Cross Product Calculator", "cross-product-calculator", "Physics"],
        ["Dot Product Calculator", "dot-product-calculator", "Physics"],
        ["Vector Magnitude Calculator", "vector-magnitude-calculator", "Physics"],
        ["Dimensional Analysis Calculator", "dimensional-analysis-calculator", "Physics"],
        ["Unit Vector Calculator", "unit-vector-calculator", "Physics"],
        ["Center of Mass Calculator", "center-of-mass-calculator", "Physics"],
        ["Vector Projection Calculator", "vector-projection-calculator", "Physics"],
        ["Gear Ratio Calculator", "gear-ratio-calculator", "Physics"],
        // Finance calculator
        ["Enterprise Value Calculator", "enterprise-value-calculator", "Finance"],
        ["EBITDA Calculator", "ebitda-calculator", "Finance"],
        ["EBIT Calculator", "ebit-calculator", "Finance"],
        ["WACC Calculator", "wacc-calculator", "Finance"],
        ["Cap Rate Calculator", "cap-rate-calculator", "Finance"],
        ["ROI Calculator", "roi-calculator", "Finance"],
        ["Cost of Equity Calculator", "cost-of-equity-calculator", "Finance"],
        ["ROAS Calculator", "roas-calculator", "Finance"],
        ["Beta Calculator", "beta-calculator", "Finance"],
        ["Cash Back Calculator", "cash-back-calculator", "Finance"],
        ["Current Ratio Calculator", "current-ratio-calculator", "Finance"],
        ["Net Worth Calculator", "net-worth-calculator", "Finance"],
        ["Opportunity Cost Calculator", "opportunity-cost-calculator", "Finance"],
        ["Salary Calculator", "salary-calculator", "Finance"],
        ["Tip Calculator", "tip-calculator", "Finance"],
        ["Overtime Calculator", "overtime-calculator", "Finance"],
        ["Pay Raise Calculator", "pay-raise-calculator", "Finance"],
        ["AGI Calculator", "agi-calculator", "Finance"],
        ["Hourly to Salary Calculator", "hourly-to-salary-calculator", "Finance"],
        ["Salary to Hourly Calculator", "salary-to-hourly-calculator", "Finance"],
        ["Gross Income Calculator", "gross-income-calculator", "Finance"],
        ["Time and a Half Calculator", "time-and-a-half", "Finance"],
        ["Labor Cost Calculator", "labor-cost-calculator", "Finance"],
        ["Monthly Income Calculator", "monthly-income-calculator", "Finance"],
        ["VA Disability Calculator", "va-disability-calculator", "Finance"],
        ["Discount Calculator", "discount-calculator", "Finance"],
        ["Margin Calculator", "profit-margin-calculator", "Finance"],
        ["Marginal Cost Calculator", "marginal-cost-calculator", "Finance"],
        ["Maximum Profit Calculator", "maximum-profit-calculator", "Finance"],
        ["Turo Calculator", "turo-calculator", "Finance"],
        ["Variable Cost Calculator", "variable-cost-calculator", "Finance"],
        ["Employee Cost Calculator", "employee-cost-calculator", "Finance"],
        ["Marginal Revenue Calculator", "marginal-revenue-calculator", "Finance"],
        ["Cost of Goods Sold Calculator", "cost-of-goods-sold-calculator", "Finance"],
        ["Contribution Margin Calculator", "contribution-margin-calculator", "Finance"],
        ["Stock Calculator", "stock-calculator", "Finance"],
        ["Commission Calculator", "commission-calculator", "Finance"],
        ["Dividend Yield Calculator", "dividend-yield-calculator", "Finance"],
        ["Options Profit Calculator", "options-profit-calculator", "Finance"],
        ["Price Calculator", "price-calculator", "Finance"],
        ["Sales Percentage Calculator", "percent-of-sales-calculator", "Finance"],
        ["Youtube Revenue Calculator", "youtube-revenue-calculator", "Finance"],
        ["CTR Calculator", "ctr-calculator", "Finance"],
        ["Unemployment Rate Calculator", "unemployment-rate-calculator", "Finance"],
        ["Growth Rate Calculator", "growth-rate-calculator", "Finance"],
        ["Comparative Advantage Calculator", "comparative-advantage-calculator", "Finance"],
        ["GDP Per Capita Calculator", "gdp-per-capita-calculator", "Finance"],
        ["GDP Calculator", "gdp-calculator", "Finance"],
        ["CAGR Calculator", "cagr-calculator", "Finance"],
        ["FIFO & LIFO Calculator", "fifo-lifo-calculator", "Finance"],
        ["CPC Calculator", "cpc-calculator", "Finance"],
        ["Margin of Error Calculator", "margin-of-error-calculator", "Finance"],
        ["CPM Calculator", "cpm-calculator", "Finance"],
        ["Payback Period Calculator", "payback-period-calculator", "Finance"],
        ["Basis Point Calculator", "basis-point-calculator", "Finance"],
        ["Markdown Calculator", "markdown-calculator", "Finance"],
        ["Rent Split Calculator", "rent-split-calculator", "Finance"],
        ["Deadweight Loss Calculator", "deadweight-loss-calculator", "Finance"],
        ["NPS Calculator", "nps-calculator", "Finance"],
        ["Rent Increase Calculator", "rent-increase-calculator", "Finance"],
        ["Money Counter Calculator", "money-counter-calculator", "Finance"],
        ["Cost Basis Calculator", "cost-basis-calculator", "Finance"],
        ["MACRS Depreciation Calculator", "macrs-depreciation-calculator", "Finance"],
        ["Depreciation Calculator", "depreciation-calculator", "Finance"],
        ["Future Value of Annuity Calculator", "future-value-of-annuity", "Finance"],
        ["Property Depreciation Calculator", "property-depreciation-calculator", "Finance"],
        ["Car Depreciation Calculator", "car-depreciation-calculator", "Finance"],
        ["Earnings Per Share Calculator", "earnings-per-share-calculator", "Finance"],
        ["Out The Door Price Calculator", "out-the-door-price-calculator", "Finance"],
        ["NPV Calculator", "npv-calculator", "Finance"],
        ["Discounted Cash Flow Calculator", "discounted-cash-flow-calculator", "Finance"],
        ["Income Tax Calculator", "tax-calculator", "Finance"],
        ["Stamp Duty Calculator", "stamp-duty-calculator", "Finance"],
        ["VAT Calculator", "vat-calculator", "Finance"],
        ["Sales Tax Calculator", "salestax-calculator", "Finance"],
        ["PayPal Fee Calculator", "paypal-fee-calculator", "Finance"],
        ["Water Bill Calculator", "water-bill-calculator", "Finance"],
        ["Reverse Sales Tax Calculator", "reverse-sales-tax-calculator", "Finance"],
        ["Price Elasticity of Demand Calculator", "price-elasticity-demand-calculator", "Finance"],
        ["Income Elasticity of Demand Calculator", "income-elasticity-of-demand-calculator", "Finance"],
        ["Consumer Surplus Calculator", "consumer-surplus-calculator", "Finance"],
        ["MPC Calculator", "mpc-calculator", "Finance"],
        ["Cross Price Elasticity Calculator", "cross-price-elasticity-calculator", "Finance"],
        ["Buying Power Calculator", "buying-power-calculator", "Finance"],
        ["Wedding Budget Calculator", "wedding-budget-calculator", "Finance"],
        ["Actual Cash Value Calculator", "actual-cash-value-calculator", "Finance"],
        ["Real Estate Commission Calculator", "real-estate-commission-calculator", "Finance"],
        ["Salvage Value Calculator", "salvage-value-calculator", "Finance"],
        ["Book Value Calculator", "book-value-calculator", "Finance"],
        // Everyday Life calculator
        ["Love Calculator", "love-calculator", "Everyday Life"],
        ["PPI Calculator", "ppi-calculator", "Everyday Life"],
        ["Aspect Ratio Calculator", "aspect-ratio-calculator", "Everyday Life"],
        ["Board Foot Calculator", "board-foot-calculator", "Everyday Life"],
        ["CBM Calculator", "cbm-calculator", "Everyday Life"],
        ["Curtain Size Calculator", "curtain-size-calculator", "Everyday Life"],
        ["Blind Size Calculator", "blind-size-calculator", "Everyday Life"],
        ["Tv Size Calculator", "tv-size-calculator", "Everyday Life"],
        ["Screen Size Calculator", "screen-size-calculator", "Everyday Life"],
        ["Batting Average Calculator", "batting-average-calculator", "Everyday Life"],
        ["Bowling Score Calculator", "bowling-score-calculator", "Everyday Life"],
        ["On Base Percentage Calculator", "on-base-percentage-calculator", "Everyday Life"],
        ["Slugging Percentage Calculator", "slugging-percentage-calculator", "Everyday Life"],
        ["Magic Number Calculator", "magic-number-calculator", "Everyday Life"],
        ["Dunk Calculator", "dunk-calculator", "Everyday Life"],
        ["ERA Calculator", "era-calculator", "Everyday Life"],
        ["Freight Class Calculator", "freight-class-calculator", "Everyday Life"],
        ["Nether Portal Calculator", "nether-portal-calculator", "Everyday Life"],
        ["eDPI Calculator", "edpi-calculator", "Everyday Life"],
        ["Visa Chance Calculator", "visa-chance-calculator", "Everyday Life"],
        ["Population Density Calculator", "population-density-calculator", "Everyday Life"],
        ["Prorated Rent Calculator", "prorated-rent-calculator", "Everyday Life"],
        ["Water Weight Calculator", "water-weight-calculator", "Everyday Life"],
        ["Stair Calculator", "stair-calculator", "Everyday Life"],
        ["MCG to MG Calculator", "mcg-to-mg-calculator", "Everyday Life"],
        ["Download Calculator", "download-calculator", "Everyday Life"],
        ["Sobriety Calculator", "sobriety-calculator", "Everyday Life"],
        ["KD Calculator", "kd-calculator", "Everyday Life"],
        ["Aquarium Calculator", "aquarium-calculator", "Everyday Life"],
        ["Data Transfer Calculator", "data-transfer-calculator", "Everyday Life"],
        ["Words per Minute Calculator", "words-per-minute-calculator", "Everyday Life"],
        ["Desk Height Calculator", "desk-height-calculator", "Everyday Life"],
        ["Plant Spacing Calculator", "plant-spacing-calculator", "Everyday Life"],
        ["Bike Size Calculator", "bike-size-calculator", "Everyday Life"],
        ["AC BTU Calculator", "ac-btu-calculator", "Everyday Life"],
        ["Ring Size Calculator", "ring-size-calculator", "Everyday Life"],
        ["Shoe Size Calculator", "shoe-size-calculator", "Everyday Life"],
        ["Gas Calculator", "gas-calculator", "Everyday Life"],
        ["Travel Time Calculator", "travel-time-calculator", "Everyday Life"],
        ["Sleep Calculator", "sleep-calculator", "Everyday Life"],
        ["Pant Size Calculator", "pant-size-calculator", "Everyday Life"],
        ["Lawn Mowing Cost Calculator", "lawn-mowing-cost-calculator", "Everyday Life"],
        ["Tire Size Calculator", "tire-size-calculator", "Everyday Life"],
        ["River Rock Calculator", "river-rock-calculator", "Everyday Life"],
        ["Circle Skirt Calculator", "circle-skirt-calculator", "Everyday Life"],
        ["Yards To Tons Calculator", "yards-to-tons-calculator", "Everyday Life"],
        ["Dilution Ratio Calculator", "dilution-ratio-calculator", "Everyday Life"],
        ["GPM Calculator", "gpm-calculator", "Everyday Life"],
        ["Average Time Calculator", "average-time-calculator", "Everyday Life"],
        ["Ceiling Fan Size Calculator", "ceiling-fan-size-calculator", "Everyday Life"],
        ["Botox Cost Calculator", "botox-cost-calculator", "Everyday Life"],
        ["Gold Cost Per Pound Calculator", "gold-cost-per-pound-calculator", "Everyday Life"],
        ["Engine Hours to Miles Calculator", "engine-hours-to-miles-calculator", "Everyday Life"],
        ["Magnification Calculator", "magnification-calculator", "Everyday Life"],
        ["Split Bill Calculator", "split-bill-calculator", "Everyday Life"],
        ["Draw Length Calculator", "draw-length-calculator", "Everyday Life"],
        ["Taper Calculator", "taper-calculator", "Everyday Life"],
        ["Battery Life Calculator", "battery-life-calculator", "Everyday Life"],
        ["Fabric Calculator", "fabric-calculator", "Everyday Life"],
        ["Semester Grade Calculator", "semester-grade-calculator", "Everyday Life"],
        ["Recessed Lighting Calculator", "recessed-lighting-calculator", "Everyday Life"],
        ["CFM Calculator", "cfm-calculator", "Everyday Life"],
        ["Box Fill Calculator", "box-fill-calculator", "Everyday Life"],
        ["Tonnage Calculator", "tonnage-calculator", "Everyday Life"],
        ["Log Weight Calculator", "log-weight-calculator", "Everyday Life"],
        ["Distance Calculator", "distance-calculator", "Everyday Life"],
        ["MPG Calculator", "mpg-calculator", "Everyday Life"],
        ["Fuel Cost Calculator", "fuel-cost-calculator", "Everyday Life"],
        ["Turkey Size Calculator", "turkey-size-calculator", "Everyday Life"],
        ["Moisture Content Calculator", "moisture-content-calculator", "Everyday Life"],
        ["Age Calculator", "age-calculator", "Everyday Life"],
        ["Age Difference Calculator", "age-difference-calculator", "Everyday Life"],
        ["Korean Age Calculator", "korean-age-calculator", "Everyday Life"],
        ["House Age Calculator", "house-age-calculator", "Everyday Life"],
        ["Birthday Calculator", "birthday-calculator", "Everyday Life"],
        ["Half Birthday Calculator", "half-birthday-calculator", "Everyday Life"],
        ["Anniversary Calculator", "anniversary-calculator", "Everyday Life"],
        //   Health Calculator
        ["BMI Calculator", "bmi-calculator", "Health"],
        ["Ideal Body Weight Calculator", "ideal-weight-calculator", "Health"],
        ["Body Fat Calculator", "body-fat-percentage-calculator", "Health"],
        ["Lean Body Mass Calculator", "lean-body-mass-calculator", "Health"],
        ["Waist to Hip Ratio Calculator", "waist-to-hip-ratio-calculator", "Health"],
        ["Waist to Height Ratio (WHtR) Calculator", "waist-to-height-ratio-calculator", "Health"],
        ["FFMI Calculator", "ffmi-calculator", "Health"],
        ["Body Shape Calculator", "body-shape-calculator", "Health"],
        ["Target Heart Rate Calculator", "target-heart-rate-calculator", "Health"],
        ["IPPT Calculator", "ippt-calculator", "Health"],
        ["Wilks Calculator", "wilks-calculator", "Health"],
        ["Pace Calculator", "pace-calculator", "Health"],
        ["Bra Size Calculator", "bra-size-calculator", "Health"],
        ["One Rep Max Calculator", "one-rep-max-calculator", "Health"],
        ["ACFT Calculator", "acft-calculator", "Health"],
        ["VO2 Max Calculator", "vo2-max-calculator", "Health"],
        ["Steps to Calories Calculator", "steps-to-calories-calculator", "Health"],
        ["Height Calculator", "height-calculator", "Health"],
        ["Jump Rope Calorie Calculator", "jump-rope-calorie-calculator", "Health"],
        ["Calories Burned Biking Calculator", "calories-burned-biking-calculator", "Health"],
        ["Steps to Miles Calculator", "steps-to-miles-calculator", "Health"],
        ["Fat Burning Heart Rate Calculator", "fat-burning-heart-rate", "Health"],
        ["Max Heart Rate Calculator", "max-heart-rate-calculator", "Health"],
        ["Treadmill Calorie Calculator", "treadmill-calorie-calculator", "Health"],
        ["Swimming Calorie Calculator", "swimming-calorie-calculator", "Health"],
        ["Rucking Calorie Calculator", "rucking-calorie-calculator", "Health"],
        ["Navy Body Fat Calculator", "navy-body-fat-calculator", "Health"],
        ["Walking Calories Calculator", "walking-calorie-calculator", "Health"],
        ["Elliptical Calorie Calculator", "elliptical-calorie-calculator", "Health"],
        ["Bench Press Calculator", "bench-press-calculator", "Health"],
        ["Ovulation Calculator", "ovulation-calculator", "Health"],
        ["Pregnancy Calculator", "pregnancy-calculator", "Health"],
        ["Implantation Calculator", "implantation-calculator", "Health"],
        ["HCG Calculator", "hcg-calculator", "Health"],
        ["Pregnancy Weight Gain Calculator", "pregnancy-weight-gain-calculator", "Health"],
        ["Allele Frequency Calculator", "allele-frequency-calculator", "Health"],
        ["Dihybrid Cross Calculator", "dihybrid-cross-calculator", "Health"],
        ["Biological Age Calculator", "biological-age-calculator", "Health"],
        ["APFT Calculator", "apft-calculator", "Health"],
        ["Blood Type Calculator", "blood-type-calculator", "Health"],
        ["Height Percentile Calculator", "height-percentile-calculator", "Health"],
        ["NNT Calculator", "nnt-calculator", "Health"],
        ["Army Body Fat Calculator", "army-body-fat-calculator", "Health"],
        ["Adjusted Body Weight Calculator", "adjusted-body-weight-calculator", "Health"],
        ["Drug Half Life Calculator", "drug-half-life-calculator", "Health"],
        ["Weight Loss Calculator", "weightloss-calculator", "Health"],
        ["TDEE Calculator", "tdee-calculator", "Health"],
        ["Macro Calculator", "macro-calculator", "Health"],
        ["RMR Calculator", "rmr-calculator", "Health"],
        ["BMR Calculator", "bmr-calculator", "Health"],
        ["Water Intake Calculator", "water-intake-calculator", "Health"],
        ["Meal Calorie Calculator", "meal-calorie-calculator", "Health"],
        ["Weight Loss Percentage Calculator", "weight-loss-percentage-calculator", "Health"],
        ["Weight Watchers Points Calculator", "weight-watchers-points-calculator", "Health"],
        ["Calorie Deficit Calculator", "calorie-deficit-calculator", "Health"],
        ["Grams To Calories Calculator", "grams-to-calories-calculator", "Health"],
        ["Protein Calculator", "protein-calculator", "Health"],
        ["Weight Gain Calculator", "weight-gain-calculator", "Health"],
        ["Maintenance Calorie Calculator", "maintenance-calorie-calculator", "Health"],
        ["Breastfeeding Calorie Calculator", "breastfeeding-calorie-calculator", "Health"],
        ["Net Carbs Calculator", "net-carbs-calculator", "Health"],
        ["Bulking Calculator", "bulking-calculator", "Health"],
        ["Food Cost Calculator", "food-cost-calculator", "Health"],
        ["Meal Planner", "meal-planner", "Health"],
        ["6 Minute Walk Test Calculator", "6-minute-walk-test", "Health"],
        ["Corrected Calcium Calculator", "corrected-calcium-calculator", "Health"],
        ["ANC Calculator", "anc-calculator", "Health"],
        ["ALC Calculator", "alc-calculator", "Health"],
        ["Reticulocyte Index Calculator", "reticulocyte-count-calculator", "Health"],
        ["Child Pugh Score Calculator", "child-pugh-calculator", "Health"],
        ["Dosage Calculator", "dosage-calculator", "Health"],
        ["Melatonin Dosage Calculator", "melatonin-dosage-calculator", "Health"],
        ["Prostate Volume Calculator", "prostate-volume-calculator", "Health"],
        ["Carboplatin Calculator", "carboplatin-calculator", "Health"],
        ["SVR Calculator", "svr-calculator", "Health"],
        ["Tinetti Calculator", "tinetti-calculator", "Health"],
        ["IV Drip Rate Calculator", "drip-rate-calculator", "Health"],
        ["Map Calculator (Mean Arterial Pressure)", "map-calculator", "Health"],
        ["Cholesterol Ratio Calculator", "cholesterol-ratio-calculator", "Health"],
        ["Paracetamol Dosage Calculator", "paracetamol-dosage-calculator", "Health"],
        ["Amoxicillin Pediatric Dosage Calculator", "amoxicillin-pediatric-dosage-calculator", "Health"],
        ["Pediatric Dose Calculator", "pediatric-dose-calculator", "Health"],
        ["BUN Creatinine Ratio Calculator", "bun-creatinine-ratio-calculator", "Health"],
        ["LDL Calculator", "ldl-calculator", "Health"],
        ["Stroke Volume Calculator", "stroke-volume-calculator", "Health"],
        ["Ast Alt Ratio Calculator", "ast-alt-ratio-calculator", "Health"],
        ["Incidence Rate Calculator", "incidence-rate-calculator", "Health"],
        ["Urine Output Calculator", "urine-output-calculator", "Health"],
        ["Bishop Score Calculator", "bishop-score-calculator", "Health"],
        ["A1C Calculator", "a1c-calculator", "Health"],
        // Math Calculator
        ["Fraction Calculator", "fraction-calculator", "Math"],
        ["Mixed Number Calculator", "mixed-number-calculator", "Math"],
        ["Fraction Simplifier Calculator", "fraction-simplifier-calculator", "Math"],
        ["Fraction to Decimal Calculator", "fraction-to-decimal-calculator", "Math"],
        ["Decimal to Fraction Calculator", "decimal-to-fraction-calculator", "Math"],
        ["Fraction to Percent Calculator", "fraction-to-percent-calculator", "Math"],
        ["Percent to Fraction Calculator", "percent-to-fraction-calculator", "Math"],
        ["Improper Fractions to Mixed Numbers Calculator", "improper-fractions-to-mixed-numbers", "Math"],
        ["Mixed Numbers to Improper Fractions Calculator", "mixed-numbers-to-improper-fractions", "Math"],
        ["LCD Calculator", "lcd-calculator", "Math"],
        ["Equivalent Fractions Calculator", "equivalent-fractions-calculator", "Math"],
        ["Comparing Fractions Calculator", "comparing-fractions-calculator", "Math"],
        ["Multiplicative Inverse Calculator", "multiplicative-inverse-calculator", "Math"],
        ["Fraction Exponent Calculator", "fraction-exponent-calculator", "Math"],
        ["Cross Multiply Calculator", "cross-multiply-calculator", "Math"],
        ["Decimal Calculator", "decimal-calculator", "Math"],
        ["Comparing Decimals Calculator", "comparing-decimals-calculator", "Math"],
        ["Pythagorean Theorem Calculator", "pythagorean-theorem-calculator", "Math"],
        ["Hypotenuse Calculator", "hypotenuse-calculator", "Math"],
        ["Triangle Calculator", "triangle-calculator", "Math"],
        ["Orthocenter Calculator", "orthocenter-calculator", "Math"],
        ["30 60 90 Triangle Calculator", "30-60-90-triangle-calculator", "Math"],
        ["SAS Triangle Calculator", "sas-triangle-calculator", "Math"],
        ["Equilateral Triangle Calculator", "equilateral-triangle-calculator", "Math"],
        ["45 45 90 Triangle Calculator", "45-45-90-triangle-calculator", "Math"],
        ["Similar Triangles Calculator", "similar-triangles-calculator", "Math"],
        ["Unit Circle Calculator", "unit-circle-calculator", "Math"],
        ["Arcsin Calculator", "arcsin-calculator", "Math"],
        ["Sine Calculator", "sine-calculator", "Math"],
        ["Arccos Calculator", "arccos-calculator", "Math"],
        ["Arctan Calculator", "arctan-calculator", "Math"],
        ["Cosine Calculator", "cosine-calculator", "Math"],
        ["Tangent Calculator", "tangent-calculator", "Math"],
        ["Secant Calculator", "secant-calculator", "Math"],
        ["Csc Calculator", "csc-calculator", "Math"],
        ["Cotangent Calculator", "cotangent-calculator", "Math"],
        ["Law of Sines Calculator", "law-of-sines-calculator", "Math"],
        ["Law of Cosines Calculator", "law-of-cosines-calculator", "Math"],
        ["Coterminal Angle Calculator", "coterminal-angle-calculator", "Math"],
        ["Double Angle Calculator", "double-angle-calculator", "Math"],
        ["Half Angle Calculator", "half-angle-calculator", "Math"],
        ["Angle Between Two Vectors Calculator", "angle-between-two-vectors-calculator", "Math"],
        ["Circumcenter Calculator", "circumcenter-calculator", "Math"],
        ["Angle of Elevation Calculator", "angle-of-elevation-calculator", "Math"],
        ["Reference Angle Calculator", "reference-angle-calculator", "Math"],
        ["Power Reducing Formula Calculator", "power-reducing-formula-calculator", "Math"],
        ["Cofunction Calculator", "cofunction-calculator", "Math"],
        ["Trigonometry Calculator", "trigonometry-calculator", "Math"],
        ["Sohcahtoa Calculator", "sohcahtoa-calculator", "Math"],
        ["Percentage Calculator", "percentage-calculator", "Math"],
        ["Percent Error Calculator", "percent-error-calculator", "Math"],
        ["Percentage Increase Calculator", "percentage-increase-calculator", "Math"],
        ["Percentage Decrease Calculator", "percentage-decrease-calculator", "Math"],
        ["Percentage Difference Calculator", "percentage-difference-calculator", "Math"],
        ["Percent to Decimal Calculator", "percent-to-decimal-calculator", "Math"],
        ["Decimal to Percent Calculator", "decimal-to-percent-calculator", "Math"],
        ["Average Percentage Calculator", "average-percentage-calculator", "Math"],
        ["Percent Change Calculator", "percentage-change-calculator", "Math"],
        ["Midpoint Calculator", "midpoint-calculator", "Math"],
        ["Slope Calculator", "slope-calculator", "Math"],
        ["Point Slope Form Calculator", "point-slope-form-calculator", "Math"],
        ["Slope Intercept Form Calculator", "slope-intercept-form-calculator", "Math"],
        ["Parallel and Perpendicular line calculator", "parallel-and-perpendicular-calculator", "Math"],
        ["Tangent Line Calculator", "tangent-line-calculator", "Math"],
        ["Midpoint Rule Calculator", "midpoint-rule-calculator", "Math"],
        ["Standard Form to Slope Intercept Form Calculator", "standard-form-to-slope-intercept-form", "Math"],
        ["Equation of a Line Calculator", "equation-of-a-line-calculator", "Math"],
        ["X and Y Intercepts Calculator", "intercepts-calculator", "Math"],
        ["Slope Percentage Calculator", "slope-percentage-calculator", "Math"],
        ["Quadratic Formula Calculator", "quadratic-formula-calculator", "Math"],
        ["Discriminant Calculator", "discriminant-calculator", "Math"],
        ["Linear Interpolation Calculator", "linear-interpolation-calculator", "Math"],
        ["Interval Notation Calculator", "interval-notation-calculator", "Math"],
        ["Binomial Theorem Calculator", "binomial-theorem-calculator", "Math"],
        ["e Calculator", "e-calculator", "Math"],
        ["Linear Approximation Calculator", "linear-approximation-calculator", "Math"],
        ["Mean Value Theorem Calculator", "mean-value-theorem-calculator", "Math"],
        ["FOIL Calculator", "foil-calculator", "Math"],
        ["Vertex Form Calculator", "vertex-form-calculator", "Math"],
        ["Convolution Calculator", "convolution-calculator", "Math"],
        ["Absolute Value Calculator", "absolute-value-calculator", "Math"],
        ["Even or Odd Function Calculator", "even-odd-function-calculator", "Math"],
        ["Synthetic Division Calculator", "synthetic-division-calculator", "Math"],
        ["Distributive Property Calculator", "distributive-property-calculator", "Math"],
        ["Polynomial Long Division Calculator", "polynomial-long-division-calculator", "Math"],
        ["Rational Expressions Calculator", "rational-expression-calculator", "Math"],
        ["Variation Calculator", "variation-calculator", "Math"],
        ["Simplify Radicals Calculator", "simplify-radicals-calculator", "Math"],
        ["Inverse Modulo Calculator", "inverse-modulo-calculator", "Math"],
        ["Solve for x Calculator", "solve-for-x-calculator", "Math"],
        ["Inequality Calculator", "inequality-calculator", "Math"],
        ["Multiplying Polynomials Calculator", "multiplying-polynomials-calculator", "Math"],
        ["Substitution Calculator", "substitution-method-calculator", "Math"],
        ["System of Equations Calculator", "system-of-equations-calculator", "Math"],
        ["Diamond Problem Solver", "diamond-calculator", "Math"],
        ["Degree and Leading Coefficient Calculator", "degree-and-leading-coefficient", "Math"],
        ["Equivalent Expressions Calculator", "equivalent-expressions-calculator", "Math"],
        ["Descartes' Rule of Signs Calculator", "descartes-rule-of-signs-calculator", "Math"],
        ["Reciprocal Calculator", "reciprocal-calculator", "Math"],
        ["Monomial Calculator", "monomial-calculator", "Math"],
        ["Product Sum Calculator", "product-sum-calculator", "Math"],
        ["Pascal's Triangle Calculator", "pascals-triangle-calculator", "Math"],
        ["Rationalize the Denominator Calculator", "rationalize-the-denominator-calculator", "Math"],
        ["Characteristic Polynomial Calculator", "characteristic-polynomial-calculator", "Math"],
        ["Length of Curve Calculator", "length-of-curve-calculator", "Math"],
        ["Rational Zeros Calculator", "rational-zeros-calculator", "Math"],
        ["Power of 10 Calculator", "power-of-10-calculator", "Math"],
        ["Square Root Curve Calculator", "square-root-curve-calculator", "Math"],
        ["Fundamental Counting Principle Calculator", "fundamental-counting-principle-calculator", "Math"],
        ["Completing The Square Calculator", "completing-the-square-calculator", "Math"],
        ["Partial Fraction Decomposition Calculator", "partial-fraction-decomposition-calculator", "Math"],
        ["Integral Calculator", "integral-calculator", "Math"],
        ["Derivative Calculator", "derivative-calculator", "Math"],
        ["Laplace Transform Calculator", "laplace-transform-calculator", "Math"],
        ["Inflection Point Calculator", "inflection-point-calculator", "Math"],
        ["Average Rate of Change Calculator", "average-rate-of-change-calculator", "Math"],
        ["Riemann Sum Calculator", "riemann-sum-calculator", "Math"],
        ["Newton's Method Calculator", "newtons-method-calculator", "Math"],
        ["Trapezoidal Rule Calculator", "trapezoidal-rule-calculator", "Math"],
        ["Euler's Method Calculator", "eulers-method-calculator", "Math"],
        ["Gradient Calculator", "gradient-calculator", "Math"],
        ["Inverse Laplace Transform Calculator", "inverse-laplace-transform-calculator", "Math"],
        ["Washer Method Calculator", "washer-method-calculator", "Math"],
        ["Shell Method Calculator", "shell-method-calculator", "Math"],
        ["Implicit Differentiation Calculator", "implicit-differentiation-calculator", "Math"],
        ["Critical Point Calculator", "critical-points-calculator", "Math"],
        ["Partial Derivative Calculator", "partial-derivative-calculator", "Math"],
        ["Area Under The Curve Calculator", "area-under-the-curve-calculator", "Math"],
        ["Second Derivative Calculator", "second-derivative-calculator", "Math"],
        ["Double Integral Calculator", "double-integral-calculator", "Math"],
        ["Triple Integral Calculator", "triple-integral-calculator", "Math"],
        ["Tangent Plane Calculator", "tangent-plane-calculator", "Math"],
        ["Product Rule Derivative Calculator", "product-rule-derivative-calculator", "Math"],
        ["Radius of Convergence Calculator", "radius-of-convergence-calculator", "Math"],
        ["Simpson's Rule Calculator", "simpsons-rule-calculator", "Math"],
        ["Curl Calculator", "curl-calculator", "Math"],
        ["Improper Integral Calculator", "improper-integral-calculator", "Math"],
        ["Divergence Calculator", "divergence-calculator", "Math"],
        ["Local Maxima and Minima Calculator", "local-maxima-and-minima-calculator", "Math"],
        ["Log and Antilog Calculator", "log-antilog-calculator", "Math"],
        ["Amplitude and Period Calculator", "amplitude-and-period-calculator", "Math"],
        ["Exponential Growth Calculator", "exponential-growth-calculator", "Math"],
        ["Log Base 2 Calculator", "log-base-2-calculator", "Math"],
        ["Exponential Function Calculator", "exponential-function-calculator", "Math"],
        ["Change Of Base Formula Calculator", "change-of-base-formula-calculator", "Math"],
        ["Composite Function Calculator", "composite-function-calculator", "Math"],
        ["Inverse Function Calculator", "inverse-function-calculator", "Math"],
        ["Function Operations Calculator", "function-operations-calculator", "Math"],
        ["Average Value of a Function Calculator", "average-value-of-function", "Math"],
        ["Domain and Range Calculator", "domain-and-range-calculator", "Math"],
        ["Limit Calculator", "limit-calculator", "Math"],
        ["Doubling Time Calculator", "doubling-time-calculator", "Math"],
        ["Time to Decimal Calculator", "time-to-decimal-calculator", "Math"],
        ["Fibonacci Calculator", "fibonacci-calculator", "Math"],
        ["Online Graphing Calculator", "graphing-calculator", "Math"],
        ["Circumference Calculator", "circumference-calculator", "Math"],
        ["Centroid Calculator", "centroid-triangle-calculator", "Math"],
        ["Distance Formula Calculator", "distance-formula-calculator", "Math"],
        ["Hemisphere Calculator", "hemisphere-calculator", "Math"],
        ["Endpoint Calculator", "endpoint-calculator", "Math"],
        ["Parabola Calculator", "parabola-calculator", "Math"],
        ["Arc Length Calculator", "arc-length-calculator", "Math"],
        ["Area Between Two Curves Calculator", "area-between-two-curves-calculator", "Math"],
        ["Polar Coordinates Calculator", "polar-coordinates-calculator", "Math"],
        ["Hyperbola Calculator", "hyperbola-calculator", "Math"],
        ["Zeros Calculator", "zeros-calculator", "Math"],
        ["Perimeter Calculator", "perimeter-calculator", "Math"],
        ["Axis of Symmetry Calculator", "axis-of-symmetry-calculator", "Math"],
        ["Dilation Calculator", "dilation-calculator", "Math"],
        ["Area of A Sector Calculator", "area-of-a-sector-calculator", "Math"],
        ["Sphere Calculator", "sphere-calculator", "Math"],
        ["Parallelogram Calculator", "parallelogram-calculator", "Math"],
        ["Polygon Calculator", "polygon-calculator", "Math"],
        ["Equation of a Circle Calculator", "equation-of-a-circle", "Math"],
        ["Ellipse Calculator", "ellipse-equation-calculator", "Math"],
        ["Area of a Semicircle Calculator", "area-of-a-semicircle", "Math"],
        ["Volume of Triangular Pyramid Calculator", "volume-of-triangular-pyramid", "Math"],
        ["Area Calculator", "area-calculator", "Math"],
        ["Surface Area Calculator", "surface-area-calculator", "Math"],
        ["Distance Between Two Points Calculator", "distance-between-two-points-calculator", "Math"],
        ["Diagonal Calculator", "diagonal-calculator", "Math"],
        ["Radius of a Circle Calculator", "radius-of-a-circle-calculator", "Math"],
        ["Point of Intersection Calculator", "point-of-intersection", "Math"],
        ["Circumference to Diameter Calculator", "circumference-to-diameter-calculator", "Math"],
        ["Volume Calculator", "volume-calculator", "Math"],
        ["Cube Root Calculator", "cube-root-calculator", "Math"],
        ["Volume of a Rectangular Prism Calculator", "volume-of-a-rectangle", "Math"],
        ["Truncated Pyramid Calculator", "truncated-pyramid-calculator", "Math"],
        ["Square Volume Calculator", "volume-of-square", "Math"],
        ["Volume of Frustum Cone Calculator", "conical-frustum-volume-calculator", "Math"],
        ["GPA Calculator", "gpa-calculator", "Math"],
        ["UC GPA Calculator", "uc-gpa-calculator", "Math"],
        ["SGPA To Percentage Calculator", "sgpa-to-percentage-calculator", "Math"],
        ["Grade Calculator", "final-grade-calculator", "Math"],
        ["Test Grade Calculator", "test-calculator", "Math"],
        ["Marks Percentage Calculator", "marks-percentage-calculator", "Math"],
        ["Determinant Calculator", "determinant-calculator", "Math"],
        ["Wronskian Calculator", "wronskian-calculator", "Math"],
        ["Jacobian Calculator", "jacobian-calculator", "Math"],
        ["Eigenvalue Calculator", "eigenvalues-calculator", "Math"],
        ["Eigenvector Calculator", "eigenvectors-calculator", "Math"],
        ["Null Space Calculator", "null-space-calculator", "Math"],
        ["Linear Independence Calculator", "linear-independence-calculator", "Math"],
        ["Matrix Multiplication Calculator", "matrix-multiplication-calculator", "Math"],
        ["RREF Calculator", "rref-calculator", "Math"],
        ["Gaussian Elimination Calculator", "gaussian-elimination-calculator", "Math"],
        ["Inverse Matrix Calculator", "inverse-matrix-calculator", "Math"],
        ["Matrix Transpose Calculator", "matrix-transpose-calculator", "Math"],
        ["Gram Schmidt Calculator", "gram-schmidt-calculator", "Math"],
        ["Gauss Seidel Method Calculator", "gauss-seidel-calculator", "Math"],
        ["Augmented Matrix Calculator", "augmented-matrix-calculator", "Math"],
        ["Elementary Matrix Calculator", "elementary-matrix-calculator", "Math"],
        ["Proportion Calculator", "proportion-calculator", "Math"],
        ["Ratio Calculator", "ratio-calculator", "Math"],
        ["Golden Ratio Calculator", "golden-ratio-calculator", "Math"],
        ["Ratio to Fraction Calculator", "ratio-to-fraction-calculator", "Math"],
        ["Prime Factorization Calculator", "prime-factorization-calculator", "Math"],
        ["Math Calculator", "online-math-calculator", "Math"],
        ["Significant Figures Calculator", "sig-fig-calculator", "Math"],
        ["Long Addition Calculator", "long-addition-calculator", "Math"],
        ["Standard Form Calculator", "standard-form-calculator", "Math"],
        ["Average Calculator", "average-calculator", "Math"],
        ["Quotient and Remainder Calculator", "remainder-calculator", "Math"],
        ["Rounding Calculator", "rounding-numbers-calculator", "Math"],
        ["Scientific Notation Calculator", "scientific-notation-calculator", "Math"],
        ["Million Billion Lakh & Crore Converter", "million-billion-lakh-crore", "Math"],
        ["LCM Calculator (Least Common Multiple)", "lcm-calculator", "Math"],
        ["GCF Calculator (Greatest Common Factor) HCF,GCD", "gcf-calculator", "Math"],
        ["Factorial Calculator", "factorial-calculator", "Math"],
        ["Exponent Calculator", "exponent-calculator", "Math"],
        ["Square Root Calculator", "square-root-calculator", "Math"],
        ["Factoring Calculator", "factoring-calculator", "Math"],
        ["Remainder Theorem Calculator", "remainder-theorem-calculator", "Math"],
        ["Difference Quotient Calculator", "difference-quotient-calculator", "Math"],
        ["Summation Calculator", "summation-calculator", "Math"],
        ["Least to Greatest Calculator", "least-to-greatest-calculator", "Math"],
        ["Rational or Irrational Calculator", "rational-or-irrational-calculator", "Math"],
        ["Unit Rate Calculator", "unit-rate-calculator", "Math"],
        ["Integer Calculator", "integer-calculator", "Math"],
        ["Combining Like Terms Calculator", "combine-like-terms-calculator", "Math"],
        ["Perfect Square Trinomial Calculator", "perfect-square-trinomial-calculator", "Math"],
        ["Additive Inverse calculator", "additive-inverse-calculator", "Math"],
        ["Weighted Average Calculator", "weighted-average-calculator", "Math"],
        ["Long Multiplication Calculator", "long-multiplication-calculator", "Math"],
        ["Divisible Calculator", "divisible-calculator", "Math"],
        ["Order of Operations Calculator", "order-of-operations-calculator", "Math"],
        ["Literal Equations Calculator", "literal-equations-calculator", "Math"],
        ["Absolute Change Calculator", "absolute-change-calculator", "Math"],
        ["Round to the Nearest Cent Calculator", "round-to-the-nearest-cent", "Math"],
        ["Arithmetic Sequence Calculator", "arithmetic-sequences-calculator", "Math"],
        ["Taylor Series Calculator", "taylor-series-calculator", "Math"],
        ["Maclaurin Series Calculator", "maclaurin-series-calculator", "Math"],
        ["Geometric Sequence Calculator", "geometric-sequence-calculator", "Math"],
        ["Power Series Calculator", "power-series-calculator", "Math"],
        ["Fourier Series Calculator", "fourier-series-calculator", "Math"],
        ["Unit Tangent Vector Calculator", "unit-tangent-vector-calculator", "Math"],
        ["Directional Derivative Calculator", "directional-derivative-calculator", "Math"],
        ["Saddle Point Calculator", "saddle-point-calculator", "Math"],
        ["Rotation Calculator", "rotation-calculator", "Math"],
        ["Vector Addition Calculator", "vector-addition-calculator", "Math"],
        ["Power Set Calculator", "power-set-calculator", "Math"],
        ["Subset Calculator", "subset-calculator", "Math"],
        ["Complex Number Calculator", "complex-number-calculator", "Math"],
        ["Truth Table Calculator", "truth-table-calculator", "Math"],
        ["Venn Diagram Calculator", "venn-diagram-calculator", "Math"],
        ["Modulo Calculator", "modulo-calculator", "Math"],
        ["Binary Calculator", "binary-calculator", "Math"],
        ["Two's Complement Calculator", "twos-complement-calculator", "Math"],
        ["One's Complement Calculator", "ones-complement-calculator", "Math"],
        ["Hex Calculator", "hex-calculator", "Math"],
        ["Base Calculator", "base-calculator", "Math"],
        ["Weeks Between Dates Calculator", "weeks-between-dates-calculator", "Math"],
        ["BSA Calculator", "bsa-calculator", "Math"],
        ["Water Intake Calculator", "water-intake-calculator", "Math"],
        ["Centor Score Calculator", "centor-score-calculator", "Math"],
        ["IU GPA Calculator", "iu-gpa-calculator", "Math"],
        ["ASU GPA Calculator", "asu-gpa-calculator", "Math"],
        ["UT GPA Calculator", "ut-gpa-calculator", "Math"],
        ["Volume of Capsule Calculator", "volume-of-capsule", "Math"],
        ["Dress Size Calculator", "dress-size-calculator", "Math"],
        ["Harris Benedict Equation Calculator", "harris-benedict-calculator", "Math"],
        ["Taco Bar Calculator", "taco-bar-calculator", "Math"],
        ["IT Ratio Calculator", "it-ratio", "Math"],
        ["Pack Year Calculator", "pack-year-calculator", "Math"],
        ["Estimated Energy Requirement Calculator", "eer-calculator", "Math"],
        ["UOG GPA Calculator", "uog-gpa-calculator", "Math"],
        ["Baby Weight Percentile Calculator", "weight-percentile-calculator", "Math"],
        ["Gay Lussac's Law Calculator", "gay-lussacs-law-calculator", "Math"],
        ["Mmol to Mg/dl Calculator", "mmol-l-to-mg-dl-calculator", "Math"],
        ["Chemical Equation Balancer", "chemical-equation-balancer-calculator", "Math"],
        ["Vorici Calculator", "vorici-chromatic-calculator", "Math"],
        ["Moment of Inertia Calculator", "moment-of-inertia-calculator", "Math"],
        ["Gravitational Force Calculator", "gravity-calculator", "Math"],
        ["dBm to Watts Calculator", "dbm-to-watts", "Math"],
        ["Angle of Deviation Calculator", "angle-of-deviation-calculator", "Math"],
        ["Joules Calculator", "joule-calculator", "Math"],
        ["Scale Factor Calculator", "scale-calculator", "Math"],
        ["Markup Calculator", "markup-calculator", "Math"],
        ["CAPM Calculator", "capm-calculator", "Math"],
        ["Bond Price Calculator", "bond-price-calculator", "Math"],
        ["Time Card Advance Calculator", "time-card-advance-calculator", "Math"],
        ["Daily Water Intake Calculator", "water-intake-calculator", "Math"],
        ["UF GPA Calculator", "uf-gpa-calculator", "Math"],
        ["ARV Calculator", "arv-calculator", "Math"],
        ["Win Percentage Calculator", "winning-percentage-calculator", "Math"],
        ["Dog Age Calculator by Breed", "dog-age-calculator", "Math"],
        ["D&D 5e Point Buy Calculator", "point-buy-calculator", "Math"],
        ["Tesla Charging Cost Calculator", "tesla-charging-calculator", "Math"],
        ["Height Compression", "compression-height-calculator", "Math"],
        ["Cost Per Mile Calculator", "cost-per-mile-driving-calculator", "Math"],
        ["Area of Shaded Region Calculator", "shaded-area-calculator", "Math"]

    ];

    public function updatedSearch($value)
    {
        $this->highlightIndex = -1;

        if (empty($value)) {
            $this->suggestions = [];
            $this->showSuggestions = false;
            return;
        }

        $value = strtolower($value);

        // Filter suggestions
        $this->suggestions = array_values(array_filter(
            $this->searchCalculators,
            function ($calc) use ($value) {
                $name = strtolower($calc[0]);
                return strpos($name, $value) === 0 || strpos($name, ' ' . $value) !== false;
            }
        ));

        // Sort suggestions - exact matches first, then word-start matches
        usort($this->suggestions, function ($a, $b) use ($value) {
            $aName = strtolower($a[0]);
            $bName = strtolower($b[0]);

            $aScore = strpos($aName, $value) === 0 ? 2 : (strpos($aName, ' ' . $value) !== false ? 1 : 0);
            $bScore = strpos($bName, $value) === 0 ? 2 : (strpos($bName, ' ' . $value) !== false ? 1 : 0);

            return $bScore <=> $aScore;
        });

        $this->showSuggestions = true;
    }


    public function moveHighlight($direction)
    {
        if (empty($this->suggestions)) return;

        if ($direction === 'up') {
            $this->highlightIndex = $this->highlightIndex <= 0
                ? count($this->suggestions) - 1
                : $this->highlightIndex - 1;
        } else {
            $this->highlightIndex = $this->highlightIndex >= count($this->suggestions) - 1
                ? 0
                : $this->highlightIndex + 1;
        }
    }

    public function selectCalculator($index = null)
    {
        $index = $index ?? $this->highlightIndex;

        if (isset($this->suggestions[$index])) {
            $this->showSuggestions = false;
            return redirect()->to('/' . $this->suggestions[$index][1]);
        }
    }

    public function highlight($text)
    {
        if (empty($this->search)) return e($text);

        $pattern = '/(' . preg_quote($this->search, '/') . ')/i';
        return preg_replace($pattern, '<strong class="text-blue-600">$0</strong>', e($text));
    }

    public function hideSuggestions()
    {
        $this->showSuggestions = false;
    }

    public function clearSearch()
    {
        $this->search = '';
        $this->suggestions = [];
        $this->showSuggestions = false;
    }


    public function render()
    {
        return view('livewire.search.calculator-search');
    }
}
